### PR TITLE
Fix multiple sensor file

### LINKED ISSUE #27: Multiple force sensors (naming convention)
What do we do in scenarios which contains multiple force sensors?
- One file per sensor: subject_N_run_R_wrench_sensor_1.csv, subject_N_run_R_wrench_sensor_2.csv, ..., subject_N_run_R_wrench_sensor_S.csv
- One file with fields differentiating the sensor the data come:  subject_N_run_R_wrench.csv

| time | sensor_1_force_x | sensor_1_force_y | sensor_1_force_z | sensor_1_torque_x | sensor_1_torque_y | sensor_1_torque_z | sensor_2_force_x | sensor_2_force_y | sensor_2_force_z | sensor_2_torque_x | sensor_2_torque_y | sensor_2_torque_z |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... |
| ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... |

or 

| time | frame| force_x | force_y | force_z | torque_x | torque_y | torque_z | frame| force_x | force_y | force_z | torque_x | torque_y | torque_z|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| ... | sensor_1| ... | ... | ... | ... | ... | ... | sensor_2| ... | ... | ... | ... | ... | ... |
| ... | sensor_1| ... | ... | ... | ... | ... | ... | sensor_1| ... | ... | ... | ... | ... | ... |

I would say the first option (one file per sensor) is more general. The second one is used if all the sensors in the tesbed shares the same acquisition interface which it is not quite common (if differet interfaces, then you wouldneed some SW to mix the data).

_Originally posted by @alfonsotecnalia in https://github.com/aremazeilles/eurobench_documentation/pull/26#issuecomment-608326430_

### PR DESCRIPTION
**Pull request by aremazeilles**
Fix #27

### CODE REVIEW

**Comment by alfonsotecnalia** [comment]
For the moment, it seems fine. Is it still a WIP?

**Comment by aremazeilles** [comment]
I think it is ok. 
What I don´t like, is that then, from the filename, we don´t know whether a file contain a single, or multiple information. But Let´s start with it....

**Comment by alfonsotecnalia** [comment]
In #27, I proposed this:
'name of the file: subject_N_run_R_wrench_tagOrID if we have files from different sensors and subject_N_run_R_wrench if only one file containing the info of all the sensors.'

**Comment by aremazeilles** [comment]
This is what I wrote in the file, but I assume we make such distinction only if the tesbed uses several force sensors. If you have a single force sensor in the experimentation, then I would not put a tag in addition to the label "wrench". 

But then, given a `[...]_wrench` file, you don´t know if it contains a single sensor reading (because the testbed only involves one), or several (because the testbed involves several sensors, and we decided to place all in a single file).

**Comment by alfonsotecnalia** [comment]
> This is what I wrote in the file, but I assume we make such distinction only if the tesbed uses several force sensors. If you have a single force sensor in the experimentation, then I would not put a tag in addition to the label "wrench".

If we find interesting to differentiate without opening then we should propose to add tag

**Comment by aremazeilles** [comment]
Let´s keep it as is, and keep in mind that possible adjustment if we see we need it...

**Pull request merged**
