### PR TITLE
WIP: Add model page

### LINKED ISSUE #20: Model specification
A lot of information regarding the general model used to represent the human pilot are split in different section and this could lead to inconsistencies. I propose to prepare a separate part or document detailing the model and its standards.

for instance: 
>Figure 2 depicts a model, the same does figure 3. Table 3 instead adds a segment: trunk (either is missing or is incorrectly named neck).  
>Moreover, table 3 seems to implicitly introduce multijoint bodies not listed (while the figures limit the model to lines): the shoulder terminates on the sternoclaviar joint, which is not a starting point for any other segment... to what is the shoulder segment attached to? do you foresee a solid body linking C7 (and/or T12) to the sternoclaviar joints?
>in fig. 2 fig.3 and table 3 the pelvis is made by three segments, while in 3.9 is treated like a rigid body

### PR DESCRIPTION
**Pull request by aremazeilles**
Fix #20

### CODE REVIEW

**Comment by aremazeilles** [comment]
ping @DavidPintoFernandez @m-lancini 

As discussed in #20, I create this file, model.adoc, and copied in it all figures related to human model.
@m-lancini, if you are not confortable with adoc format, feel free sending me word file that I could insert myself in here.

Once advanced, I will remove the model-related content form the data format file, and refer to this new file.

**Comment by m-lancini** [comment]
> ping @DavidPintoFernandez @m-lancini
> 
> As discussed in #20, I create this file, model.adoc, and copied in it all figures related to human model.
> @m-lancini, if you are not confortable with adoc format, feel free sending me word file that I could insert myself in here.
> Once advanced, I will remove the model-related content form the data format file, and refer to this new file.

I think it now works. If it's ok with everybody you can merge them.

**Comment by aremazeilles** [comment]
Thanks @m-lancini for your contribution, very appreciated!
I made some simple adjustment (since the angles are defined in file `model.adoc`, I removed them from file `data_format.adoc`.

We may need some further adjustments although:

1. In `data_format.adoc`, we define the [human anthropometric file](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/data_format.adoc#33-human-anthropometric-measures-file), and we provide a table of body segment and joints. I think we should now refer to the `model` file, [section 2](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/model.adoc#human-body-segment), where the same table is provided.

2. The [joint angle file](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/data_format.adoc#61-joint-angles-file), the [joint torque file](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/data_format.adoc#61-joint-angles-file) and the [joint center 3D trajectory file](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/data_format.adoc#63-joint-center-3d-trajectories-file) should refer to the joint description in the [model file](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/model.adoc#1-joint-centers). 

Would you agree with these changes ? If yes, I can do them.
Do you think I would be missing other connection/ cross references  in between `model.adoc` and `data_format.adoc`?

**Comment by aremazeilles** [comment]
From #20, @m-lancini mentioned:

> I tried to update at least the definition of the segments. Now it seems to me it's more coherent.
The only issue is the definition of the "w" key labels. Why is that a suffix and "r" and "l_" are prefixes?

I guess your refer to the [body segment table](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/model.adoc#2-human-body-segment), is it correct? Effectively there we see `pelvis_w`, `torso_w` and `back_w`. 
If this is a standard (i.e. frequently used) label I would leave as is.
What is your opinion?

From the discussion we had in the issue page #20, are there any extension of the current version needed? Are we happy with the current figure?
ping @DavidPintoFernandez

**Comment by m-lancini** [comment]
> > The only issue is the definition of the "w" key labels. Why is that a suffix and "r" and "l_" are prefixes?
 
> I guess your refer to the [body segment table](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/model.adoc#2-human-body-segment), is it correct? Effectively there we see `pelvis_w`, `torso_w` and `back_w`.
> If this is a standard (i.e. frequently used) label I would leave as is.
> What is your opinion?

I think it's not at all common, but manageable. Generally I find it more common the _r _l suffixes instead of r_ l_ prefixes. It was just a suggestion to have either all suffixes or prefixes.

> 
> From the discussion we had in the issue page #20, are there any extension of the current version needed? Are we happy with the current figure?
> ping @DavidPintoFernandez

**Comment by aremazeilles** [comment]
OK so you would rather use suffixes, like `knee_r` instead of `r_knee`, which would be aligned with the one using also `_w` as suffix, is that correct?

@DavidPintoFernandez diegotorricelli, would this make sense?

Note that the 2 figures in [model.adoc](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/model.adoc#Human%20model) should be edited to contemplate that change then

**Comment by aremazeilles** [comment]
I would suggest to merge this and eventually to open an issue for discussing on the prefix/suffix point appart. 

Would you agree?

**Comment by m-lancini** [comment]
I agree

**Comment by DavidPintoFernandez** [comment]
> Thanks @m-lancini for your contribution, very appreciated!
> I made some simple adjustment (since the angles are defined in file `model.adoc`, I removed them from file `data_format.adoc`.
> 
> We may need some further adjustments although:
> 
> 1. In `data_format.adoc`, we define the [human anthropometric file](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/data_format.adoc#33-human-anthropometric-measures-file), and we provide a table of body segment and joints. I think we should now refer to the `model` file, [section 2](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/model.adoc#human-body-segment), where the same table is provided.
> 2. The [joint angle file](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/data_format.adoc#61-joint-angles-file), the [joint torque file](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/data_format.adoc#61-joint-angles-file) and the [joint center 3D trajectory file](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/data_format.adoc#63-joint-center-3d-trajectories-file) should refer to the joint description in the [model file](https://github.com/aremazeilles/eurobench_documentation/blob/model_apart/model.adoc#1-joint-centers).
> 
> Would you agree with these changes ? If yes, I can do them.
> Do you think I would be missing other connection/ cross references in between `model.adoc` and `data_format.adoc`?

I agree on this changes

**Comment by m-lancini** [comment]
Thanks David. I agree with the changes. I don't see any other connection right now.

**Pull request merged**
