### PR TITLE
use table for format spec

### LINKED ISSUE #19: joints angle file structure
Original:
> 1st row: header with M+1 labels were M = number of angles considered.

I think the text used for the torques is better understood:
>1st row: header with (3*M)+1 labels were M = number of joints.

### PR DESCRIPTION
**Pull request by aremazeilles**
fix #19

### CODE REVIEW

**Comment by aremazeilles** [comment]
I saw some inconsistencies in data format (time in seconds / ms ), and some labels are not clear, but I would as usual suggest looking at it in separate branch

**Comment by alfonsotecnalia** [comment]
joint angles order is YXZ. I suggest to keep this order in the fields

**Comment by alfonsotecnalia** [comment]
Also meters and mm. But as you suggested could do it in another thread

**Comment by aremazeilles** [comment]
With respect to the column order, ok with your change, but the order in the file should not reflect any mathematical meaning, right?

Are you happy with these changes? Should we merge, and create issues for m  mm, and use of degrees?

**Pull request merged**
