### PR TITLE
Add wrench format

### LINKED ISSUE #22: Ground reaction forces
section 4.4. Ground Reaction Forces file states that the GRF file shall contain forces measured by force platforms.
We also measure GRFs from crutches, when they are used, so we have more GRFs.
Shall we save the GRFs of the crutches in the same file or shall we foresee a file template for reaction forces not at the feet? 
I imagine this is not limited to crutches but also instrumented steps and handrails also could express the forces between the pilot and the environment as reaction forces.

### PR DESCRIPTION
**Pull request by aremazeilles**
Fix #22

### CODE REVIEW

**Comment by aremazeilles** [comment]
Ping @alfonsotecnalia @m-lancini 
What do you think?

As mentioned in #19, I propose a table representation of the information for the file. Looks like more clear to me.

**Comment by m-lancini** [comment]
are x, y, z relative to the body the sensor is attached to or absolute? I'd say the first, but then we also need to specify the body

**Comment by aremazeilles** [comment]
I would assume that the force is relative to the sensing point. It is for sure relative to the body it is attached to. But this may not be expressed in the body frame, rather in the sensor frame. Do yo agree?

**Comment by alfonsotecnalia** [comment]
I agree, it would be relative (to the sensor frame of reference).

What do we do in scenarios which contains multiple force sensors?
- One file per sensor: subject_N_run_R_wrench_sensor_1.csv, subject_N_run_R_wrench_sensor_2.csv, ..., subject_N_run_R_wrench_sensor_S.csv
- One file with fields differentiating the sensor the data come:  subject_N_run_R_wrench.csv

| time | sensor_1_force_x | sensor_1_force_y | sensor_1_force_z | sensor_1_torque_x | sensor_1_torque_y | sensor_1_torque_z | sensor_2_force_x | sensor_2_force_y | sensor_2_force_z | sensor_2_torque_x | sensor_2_torque_y | sensor_2_torque_z |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... |
| ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... |

or 

| time | frame| force_x | force_y | force_z | torque_x | torque_y | torque_z | frame| force_x | force_y | force_z | torque_x | torque_y | torque_z|
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| ... | sensor_1| ... | ... | ... | ... | ... | ... | sensor_2| ... | ... | ... | ... | ... | ... |
| ... | sensor_1| ... | ... | ... | ... | ... | ... | sensor_1| ... | ... | ... | ... | ... | ... |

I would say the first option (one file per sensor) is more general. The second one is used if all the sensors in the tesbed shares the same acquisition interface which it is not quite common (if differet interfaces, then you wouldneed some SW to mix the data).

**Comment by aremazeilles** [comment]
I would suggest looking at the mutliple sensor aspect aside, in another issue, to avoid mixing topics.

**Comment by aremazeilles** [comment]
If we are happy with the proposed Wrench Stamped description, then we merge it, deploy the format description per table in all files, and then consider other issues, such as the multiple sensors one.

**Comment by m-lancini** [comment]
> I would assume that the force is relative to the sensing point. It is for sure relative to the body it is attached to. But this may not be expressed in the body frame, rather in the sensor frame. Do yo agree?

I think in most cases the force sensors will be fixed, so it makes little difference, for mobile force sensors (I am thinking about crutches), forces and torques should be expressed in terms of the reference frame of the body (i.e. the object) the sensor is rigidly attached to. It would make inverse dynamic easier.

**Comment by m-lancini** [comment]
> If we are happy with the proposed Wrench Stamped description, then we merge it, deploy the format description per table in all files, and then consider other issues, such as the multiple sensors one.

We are measuring only forces and not torques in our project. Do we skip the torque columns? fill them with 0? or fill them with NaN?

**Comment by alfonsotecnalia** [comment]
0 could be interpreted as if there was a measuremet but it was 0. I think that NaN is specific to numbers and some fields in other files could contain strings. I would leave them empty/blank.

**Comment by alfonsotecnalia** [comment]
I would add "empty fields" to issues and merge this request.

**Pull request merged**
